name: dwgth4i

description: I enjoy doing boot2root lab/box

avatar: "https://raw.githubusercontent.com/dwgth4i/blogs/refs/heads/main/images/reze.jpg"

theme: minima

footer-links:
  github: dwgth4i
  twitter: dwgth4i
  instagram: dwgth4i

baseurl: "/blogs"
