title: "dwgth4i's blog"
author: "dwgth4i"

description: I enjoy doing boot2root lab/box

theme: minima

footer-links:
  github: dwgth4i
  twitter: dwgth4i
  instagram: dwgth4i

baseurl: "/blogs"
