title: "dwgth4i's blog"
author: "dwgth4i"

description: "Red teaming, Windows enjoyer"

theme: minima

avatar: "https://raw.githubusercontent.com/dwgth4i/blogs/refs/heads/main/assets/images/reze.jpg"
